### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'myrule'

### ISSUE THREAD

**Issue by walkingway** [cloverstd/GFWList2Surge#2]
Traceback (most recent call last):
  File "main.py", line 238, in <module>
    main()
  File "main.py", line 196, in main
    with open(args.user_rule, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'myrule'

**Comment by cloverstd** [comment]
@walkingway 
Just remove `--user-rule` arguments when you do not need
