### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'gfwlist.txt'

### ISSUE THREAD

**Issue by tanbofan** [cloverstd/GFWList2Surge#3]
tanbofandeMacBook-Pro:GFWList2Surge tanbofan$ python main.py -i gfwlist.txt -f surge.conf -p "SOCKS5 192.168.1.17:1080;" --user-rule myrule --surge-proxy-name "proxy1" "proxy2" --surge-proxy "custom, 1.2.3.4, 443, rc4-md5, password" "custom, 1.2.3.4, 443, rc4-md5, password" --apple-dns apple-cdn-speed.report
Traceback (most recent call last):
  File "main.py", line 238, in <module>
    main()
  File "main.py", line 187, in main
    with open(args.input, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'gfwlist.txt'

**Comment by cloverstd** [comment]
@tanbofan 
You should download gfwlist.txt first.

https://github.com/gfwlist/gfwlist
